package com.myide.backend.service.template;

import com.myide.backend.domain.LanguageType;
import com.myide.backend.domain.workspace.TemplateType;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

@Slf4j
@Component
public class NextTemplateStrategy implements ProjectTemplateStrategy {

    @Override
    public boolean supports(TemplateType templateType) {
        return templateType == TemplateType.NEXT;
    }

    @Override
    public void generateTemplate(Path projectRoot, LanguageType language) throws IOException {
        log.info("▲ Next.js TypeScript 템플릿 생성 시작");

        Path appDir = projectRoot.resolve("app");
        Path publicDir = projectRoot.resolve("public");

        Files.createDirectories(appDir);
        Files.createDirectories(publicDir);

        createPackageJson(projectRoot);
        createNextConfig(projectRoot);
        createTsConfig(projectRoot);
        createNextEnv(projectRoot);
        createLayout(appDir);
        createPage(appDir);
        createGlobalsCss(appDir);
        createGitIgnore(projectRoot);
        createReadme(projectRoot);

        log.info("▲ Next.js TypeScript 템플릿 파일 세팅 완료");
    }

    private void createPackageJson(Path projectRoot) throws IOException {
        String packageJson = """
                {
                  "name": "wevais-next-app",
                  "version": "1.0.0",
                  "private": true,
                  "scripts": {
                    "dev": "next dev -H 0.0.0.0 -p 3001",
                    "start": "next start -H 0.0.0.0 -p 3001",
                    "build": "next build",
                    "lint": "next lint"
                  },
                  "dependencies": {
                    "next": "^15.0.0",
                    "react": "^19.0.0",
                    "react-dom": "^19.0.0"
                  },
                  "devDependencies": {
                    "typescript": "^5.0.0",
                    "@types/node": "^22.0.0",
                    "@types/react": "^19.0.0",
                    "@types/react-dom": "^19.0.0"
                  }
                }
                """;

        Files.writeString(projectRoot.resolve("package.json"), packageJson);
    }

    private void createNextConfig(Path projectRoot) throws IOException {
        String nextConfig = """
                /** @type {import('next').NextConfig} */
                const nextConfig = {};

                export default nextConfig;
                """;

        Files.writeString(projectRoot.resolve("next.config.mjs"), nextConfig);
    }

    private void createTsConfig(Path projectRoot) throws IOException {
        String tsConfig = """
                {
                  "compilerOptions": {
                    "target": "ES2017",
                    "lib": ["dom", "dom.iterable", "esnext"],
                    "allowJs": true,
                    "skipLibCheck": true,
                    "strict": true,
                    "noEmit": true,
                    "esModuleInterop": true,
                    "module": "esnext",
                    "moduleResolution": "bundler",
                    "resolveJsonModule": true,
                    "isolatedModules": true,
                    "jsx": "preserve",
                    "incremental": true,
                    "plugins": [
                      {
                        "name": "next"
                      }
                    ],
                    "paths": {
                      "@/*": ["./*"]
                    }
                  },
                  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
                  "exclude": ["node_modules"]
                }
                """;

        Files.writeString(projectRoot.resolve("tsconfig.json"), tsConfig);
    }

    private void createNextEnv(Path projectRoot) throws IOException {
        String nextEnv = """
                /// <reference types="next" />
                /// <reference types="next/image-types/global" />

                // NOTE: This file should not be edited.
                // See https://nextjs.org/docs/app/api-reference/config/typescript for more information.
                """;

        Files.writeString(projectRoot.resolve("next-env.d.ts"), nextEnv);
    }

    private void createLayout(Path appDir) throws IOException {
        String layoutTsx = """
                import type { Metadata } from "next";
                import "./globals.css";

                export const metadata: Metadata = {
                  title: "WEVAIS Next App",
                  description: "Next.js TypeScript template generated by WEVAIS",
                };

                export default function RootLayout({
                  children,
                }: Readonly<{
                  children: React.ReactNode;
                }>) {
                  return (
                    <html lang="ko">
                      <body>{children}</body>
                    </html>
                  );
                }
                """;

        Files.writeString(appDir.resolve("layout.tsx"), layoutTsx);
    }

    private void createPage(Path appDir) throws IOException {
        String pageTsx = """
                export default function Home() {
                  return (
                    <main className="page">
                      <section className="card">
                        <p className="badge">Next.js TypeScript Template</p>

                        <h1>WEVAIS Next App</h1>

                        <p className="description">
                          React 기반 Next.js 프로젝트입니다. App Router와 TypeScript 구조로 생성되었습니다.
                        </p>

                        <div className="infoBox">
                          <p>
                            <strong>실행 명령어</strong>
                          </p>
                          <code>npm run dev</code>
                        </div>
                      </section>
                    </main>
                  );
                }
                """;

        Files.writeString(appDir.resolve("page.tsx"), pageTsx);
    }

    private void createGlobalsCss(Path appDir) throws IOException {
        String globalsCss = """
                * {
                  box-sizing: border-box;
                }

                html,
                body {
                  margin: 0;
                  padding: 0;
                  min-height: 100%;
                  font-family: Arial, Helvetica, sans-serif;
                  background: #f8fafc;
                  color: #111827;
                }

                .page {
                  min-height: 100vh;
                  display: flex;
                  align-items: center;
                  justify-content: center;
                  padding: 40px;
                }

                .card {
                  width: min(560px, 100%);
                  padding: 40px;
                  border-radius: 24px;
                  background: white;
                  box-shadow: 0 20px 60px rgba(15, 23, 42, 0.12);
                  text-align: center;
                }

                .badge {
                  display: inline-flex;
                  margin: 0 0 16px;
                  padding: 6px 12px;
                  border-radius: 999px;
                  background: #ecfeff;
                  color: #0891b2;
                  font-size: 13px;
                  font-weight: 700;
                }

                h1 {
                  margin: 0;
                  font-size: 38px;
                  letter-spacing: -0.04em;
                }

                .description {
                  margin: 16px 0 28px;
                  color: #6b7280;
                  line-height: 1.6;
                }

                .infoBox {
                  padding: 16px;
                  border-radius: 16px;
                  background: #f1f5f9;
                  text-align: left;
                }

                .infoBox p {
                  margin: 0 0 8px;
                }

                code {
                  display: inline-block;
                  padding: 6px 10px;
                  border-radius: 8px;
                  background: #0f172a;
                  color: white;
                  font-size: 14px;
                }
                """;

        Files.writeString(appDir.resolve("globals.css"), globalsCss);
    }

    private void createGitIgnore(Path projectRoot) throws IOException {
        String gitignore = """
                node_modules
                .next
                out
                .env
                .env.local
                npm-debug.log*
                yarn-debug.log*
                yarn-error.log*
                """;

        Files.writeString(projectRoot.resolve(".gitignore"), gitignore);
    }

    private void createReadme(Path projectRoot) throws IOException {
        String readme = """
                # WEVAIS Next App

                Next.js App Router 기반 TypeScript 프로젝트입니다.

                ## 실행 방법

                ```bash
                npm install
                npm run dev
                ```

                기본 실행 주소는 `http://localhost:3000`입니다.
                """;

        Files.writeString(projectRoot.resolve("README.md"), readme);
    }
}