# src/main/resources/application-secret.yml
google:
  gemini:
    api-key: "AIzaSyBElgN0XoWv-VC4dgwaRCq56U_OkY330wo"
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"