# src/main/resources/application-secret.yml
google:
  gemini:
    api-key: "AIzaSyCkiic5Rl27ILoR9NVPkouVpI2hIXrxyZk"
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"